---
- name: Install Vault | Requirements | Install docker python package
  become: true
  become_user: "{{  rv_hashicorp_vault_os_user  }}"
  pip:
    name: docker
    extra_args: --user
    executable: pip3
