---
- name: Install Vault | Requirements | Upgrade and Install basic services
  include_role:
    name: sourceshift.linux_patching

- name: Install Vault | Requirements | Set Basic SSHD Configuration
  include_role:
    name: sourceshift.ssh_hardening

- name: Install Vault | Requirements | Create User for Vault
  include_role:
    name: sourceshift.user_add
  vars:
    rv_user_add_username: "{{ rv_hashicorp_vault_os_user }}"
    rv_user_add_user_nopasswd_commands: ["ALL"]

- name: Install Vault | Requirements | Install Docker
  include_role:
    name: geerlingguy.docker
  vars:
    docker_users: ["{{ rv_hashicorp_vault_os_user }}"]
    docker_package_state: present

- name: Install Vault | Requirements | Workspace
  include_role:
    name: sourceshift.server_workspace

- name: Install Vault | Requirements | Install docker python package
  become: true
  become_user: "{{  rv_hashicorp_vault_os_user  }}"
  pip:
    name: docker
    extra_args: --user
    executable: pip3
